### ISSUE TITLE
Instruction SLLI executes even without the 7 MSbits being 0

### ISSUE THREAD

**Issue by VJBMario** [ul-lar/Adept-TestFiles#3]
The instruction SLLI  should have the following format: 
0000000 | shamt | rs1 | 001 | rd | 0010011

The issue is related with the  7 most significant bits that actually are indifferent to the execution of the instruction. For instance, if the assembly instruction "slli a3, a1, 4" are written it generates in .hex the code "0x00459693" and the instruction is correctly executed, but if in the .hex appear, for instance "0x20459693", the instruction is still correctly executed what shouldn't happen because the 7 MSB are not set to zero as specified in instruction set.

**Comment by lfiolhais** [comment]
Issue moved to ul-lar/Adept#2
